import cv2
import os

image_path = r"C:\Users\krish\.gemini\antigravity-ide\brain\c2d211b4-39c9-456f-837b-b153b8e9d4c7\hardware_drone_prototype_1788618450116.jpg"
output_video_path = r"C:\Users\krish\OneDrive\Desktop\ml-sahyog\test_hostage_video.mp4"

def create_video():
    img = cv2.imread(image_path)
    if img is None:
        print("Failed to load image.")
        return

    # The white paper is roughly at the bottom right.
    # Let's add text in the center of the paper area.
    # Image size is likely 1024x1024 (generated by default).
    # We'll put text roughly at x=650, y=700
    
    font = cv2.FONT_HERSHEY_SIMPLEX
    text = "SAHYOG-8492"
    position = (600, 750)
    font_scale = 1.5
    font_color = (0, 0, 0) # Black text
    thickness = 4

    cv2.putText(img, text, position, font, font_scale, font_color, thickness, cv2.LINE_AA)

    # Save to a video file
    height, width, layers = img.shape
    fps = 30
    duration_sec = 3
    
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    video = cv2.VideoWriter(output_video_path, fourcc, fps, (width, height))

    print(f"Generating a {duration_sec}-second video...")
    for _ in range(fps * duration_sec):
        video.write(img)

    video.release()
    print(f"Video saved successfully to {output_video_path}")

if __name__ == "__main__":
    create_video()
